### ISSUE TITLE
Lake Michigan is completely inside the political borders of the United States

### ISSUE THREAD

**Issue by tewhalen** [conjugateprior/cbp-border-zone#1]
see https://en.wikipedia.org/wiki/Lake_Michigan.  

Wisconsin, Illinois, Indiana, and Michigan have no international border adjacent to Lake Michigan.

**Comment by andyanderson** [comment]
I agree; your analysis should start at the designated boundary between the US and Canada, which is roughly down the middle of Lakes Superior, Huron, Erie, and Ontario; Lake Michigan is a completely territorial water of the United States.

More generally, according to the regulation, the “external boundary” begins 12 nautical miles out to sea, so that’s where you should start.

Here’s the regulation; there’s a loophole as described in section (b), but unless you have additional information from the CPB, your analysis needs to be revised and corrected as above.

§ Sec. 287.1 Definitions.

(a)

(1) External boundary . The term external boundary, as used in section 287(a)(3) of the Act, means the land boundaries and the territorial sea of the United States extending 12 nautical miles from the baselines of the United States determined in accordance with international law.

(2) Reasonable distance . The term "reasonable distance," as used in section 287(a) (3) of the Act, means within 100 air miles from any external boundary of the United States or any shorter distance which may be fixed by the chief patrol agent for CBP, or the special agent in charge for ICE, or, so far as the power to board and search aircraft is concerned any distance fixed pursuant to paragraph (b) of this section. (Amended 6/13/03; 68 FR 35273 )

(b) Reasonable distance; fixing by chief patrol agents and special agents in charge . In fixing distances not exceeding 100 air miles pursuant to paragraph (a) of this section, chief patrol agents and special agents in charge shall take into consideration topography, confluence of arteries of transportation leading from external boundaries, density of population, possible inconvenience to the traveling public, types of conveyances used, and reliable information as to movements of persons effecting illegal entry into the United States: Provided , That whenever in the opinion of a chief patrol agent or special agent in charge a distance in his or her sector or district of more than 100 air miles from any external boundary of the United States would because of unusual circumstances be reasonable, such chief patrol agent or special agent in charge shall forward a complete report with respect to the matter to the Commissioner of CBP, or the Assistant Secretary for ICE, as appropriate, who may, if he determines that such action is justified, declare su ch distance to be reasonable. (Revised 6/13/03; 68 FR 35273 )

https://www.uscis.gov/ilink/docView/SLB/HTML/SLB/0-0-0-1/0-0-0-11261/0-0-0-29853/0-0-0-29859.html

**Comment by conjugateprior** [comment]
PRs welcome.

**Comment by broofa** [comment]
As an opensource project maintainer, I appreciate and respect the "PRs welcome" response here, however this is a **serious** issue.  It affects not just the Great Lakes, but both coasts as well (especially around Seattle, San Francisco and Delaware).  And it invalidates most of the analysis and maps in your README.  😢

Worse, this error is propagating into the mainstream conversation about the influence of the CBP.  The ACLU and ESRI (via CityLab) have all published maps based on this work, and those maps have in turn been picked up by [other media outlets](https://www.google.com/search?q=100-mile+border+map).

Prior to finding my way here I noticed the issues @andyanderson points out and put together my own map showing [how significant an error this is](https://imgur.com/gallery/Xm2pGUv).  I've reached out to ACLU and CityLab about this but received no response.  I'm also thinking I should post this to https://www.reddit.com/r/dataisbeautiful/ at some point, but wanted to reach out to you first.

Thoughts?

P.S.  Would this [US maritime boundaries dataset from NOAA](https://data.noaa.gov/dataset/dataset/maritime-limits-and-boundaries-of-united-states-of-america/resource/3ea9ff3c-0328-40bd-9eaf-4a590603d939) [KMZ file] be helpful?

**Comment by tcely** [comment]
Apparently the entire state of Michigan is included according to this fact sheet:

http://www.aclumich.org/sites/default/files/Fact%20sheet_100_Mile_Zone.pdf

http://www.aclumich.org/article/100-mile-zone-need-more-transparent-us-customs-and-border-patrol

**Comment by conjugateprior** [comment]
Just finally coming back to this. Interesting discussion.

[This](http://www.aclumich.org/sites/default/files/100%20mile%20zone%20map.PNG) from the complaint linked by @tcely *does* end up looking rather like what the code here generates, albeit mostly by accident. 

It would be nice if the ACLU were successful in finding where the CBP believes its limits, if any, actually are in each state, so we could all draw the right map. That would certainly be more useful than knowing where their limits are supposed to be, which I agree are probably not where we've all been drawing them.

**Comment by andyanderson** [comment]
100 miles from the border does include almost all of Michigan. Only the southern most part of the UP and the westernmost part of the LP lie outside. If CBP feels it can work throughout the entire state I imagine that’s something that could be challenged in court, e.g. after they execute a raid in Grand Rapids.

**Comment by conjugateprior** [comment]
@andyanderson Seems like they did already challenge. Do we know how [this case](https://www.courthousenews.com/wp-content/uploads/2016/12/ACLUMichigan.pdf) turned out? The relevant map is page 13. (Some informal reporting [here](https://www.courthousenews.com/aclu-claims-michigan-border-searches-go-too-far/))

**Comment by tcely** [comment]
@conjugateprior http://www.aclumich.org/article/all-michigan-warrantless-border-zone

No results yet from that case as far as I can tell.

**Comment by conjugateprior** [comment]
Borders are substantially correct, albeit by accident, per maps from the CBP who, as usual, do whatever they like.
